### ISSUE TITLE
input_data.csv isn't true csv.

### ISSUE THREAD

**Issue by 2DKot** [Hesowcharov/scaNeuroNet#1]
According to [RFC 4180 ](http://www.rfc-editor.org/rfc/rfc4180.txt), fields of records in CSV file must be separated by %x2C (','). But fields in input_data.csv separated by %x3B (';').

**Comment by Hesowcharov** [comment]
I have fixed it. Thanks!
[aa952fb](https://github.com/Hesowcharov/scaNeuroNet/commit/aa952fb5df9b32a4ddbd48c2abbb4295664fc59b)
